// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: find_path.proto
#ifndef GRPC_find_5fpath_2eproto__INCLUDED
#define GRPC_find_5fpath_2eproto__INCLUDED

#include "find_path.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace routing {
namespace v1 {

class PathService final {
 public:
  static constexpr char const* service_full_name() {
    return "routing.v1.PathService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status FindShortestPath(::grpc::ClientContext* context, const ::routing::v1::StartAndEndCoordinates& request, ::routing::v1::ShortestPathResult* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::routing::v1::ShortestPathResult>> AsyncFindShortestPath(::grpc::ClientContext* context, const ::routing::v1::StartAndEndCoordinates& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::routing::v1::ShortestPathResult>>(AsyncFindShortestPathRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::routing::v1::ShortestPathResult>> PrepareAsyncFindShortestPath(::grpc::ClientContext* context, const ::routing::v1::StartAndEndCoordinates& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::routing::v1::ShortestPathResult>>(PrepareAsyncFindShortestPathRaw(context, request, cq));
    }
    virtual ::grpc::Status FindTimeOptimalPath(::grpc::ClientContext* context, const ::routing::v1::StartAndEndCoordinates& request, ::routing::v1::ShortestPathResult* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::routing::v1::ShortestPathResult>> AsyncFindTimeOptimalPath(::grpc::ClientContext* context, const ::routing::v1::StartAndEndCoordinates& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::routing::v1::ShortestPathResult>>(AsyncFindTimeOptimalPathRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::routing::v1::ShortestPathResult>> PrepareAsyncFindTimeOptimalPath(::grpc::ClientContext* context, const ::routing::v1::StartAndEndCoordinates& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::routing::v1::ShortestPathResult>>(PrepareAsyncFindTimeOptimalPathRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void FindShortestPath(::grpc::ClientContext* context, const ::routing::v1::StartAndEndCoordinates* request, ::routing::v1::ShortestPathResult* response, std::function<void(::grpc::Status)>) = 0;
      virtual void FindShortestPath(::grpc::ClientContext* context, const ::routing::v1::StartAndEndCoordinates* request, ::routing::v1::ShortestPathResult* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void FindTimeOptimalPath(::grpc::ClientContext* context, const ::routing::v1::StartAndEndCoordinates* request, ::routing::v1::ShortestPathResult* response, std::function<void(::grpc::Status)>) = 0;
      virtual void FindTimeOptimalPath(::grpc::ClientContext* context, const ::routing::v1::StartAndEndCoordinates* request, ::routing::v1::ShortestPathResult* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::routing::v1::ShortestPathResult>* AsyncFindShortestPathRaw(::grpc::ClientContext* context, const ::routing::v1::StartAndEndCoordinates& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::routing::v1::ShortestPathResult>* PrepareAsyncFindShortestPathRaw(::grpc::ClientContext* context, const ::routing::v1::StartAndEndCoordinates& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::routing::v1::ShortestPathResult>* AsyncFindTimeOptimalPathRaw(::grpc::ClientContext* context, const ::routing::v1::StartAndEndCoordinates& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::routing::v1::ShortestPathResult>* PrepareAsyncFindTimeOptimalPathRaw(::grpc::ClientContext* context, const ::routing::v1::StartAndEndCoordinates& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status FindShortestPath(::grpc::ClientContext* context, const ::routing::v1::StartAndEndCoordinates& request, ::routing::v1::ShortestPathResult* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::routing::v1::ShortestPathResult>> AsyncFindShortestPath(::grpc::ClientContext* context, const ::routing::v1::StartAndEndCoordinates& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::routing::v1::ShortestPathResult>>(AsyncFindShortestPathRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::routing::v1::ShortestPathResult>> PrepareAsyncFindShortestPath(::grpc::ClientContext* context, const ::routing::v1::StartAndEndCoordinates& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::routing::v1::ShortestPathResult>>(PrepareAsyncFindShortestPathRaw(context, request, cq));
    }
    ::grpc::Status FindTimeOptimalPath(::grpc::ClientContext* context, const ::routing::v1::StartAndEndCoordinates& request, ::routing::v1::ShortestPathResult* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::routing::v1::ShortestPathResult>> AsyncFindTimeOptimalPath(::grpc::ClientContext* context, const ::routing::v1::StartAndEndCoordinates& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::routing::v1::ShortestPathResult>>(AsyncFindTimeOptimalPathRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::routing::v1::ShortestPathResult>> PrepareAsyncFindTimeOptimalPath(::grpc::ClientContext* context, const ::routing::v1::StartAndEndCoordinates& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::routing::v1::ShortestPathResult>>(PrepareAsyncFindTimeOptimalPathRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void FindShortestPath(::grpc::ClientContext* context, const ::routing::v1::StartAndEndCoordinates* request, ::routing::v1::ShortestPathResult* response, std::function<void(::grpc::Status)>) override;
      void FindShortestPath(::grpc::ClientContext* context, const ::routing::v1::StartAndEndCoordinates* request, ::routing::v1::ShortestPathResult* response, ::grpc::ClientUnaryReactor* reactor) override;
      void FindTimeOptimalPath(::grpc::ClientContext* context, const ::routing::v1::StartAndEndCoordinates* request, ::routing::v1::ShortestPathResult* response, std::function<void(::grpc::Status)>) override;
      void FindTimeOptimalPath(::grpc::ClientContext* context, const ::routing::v1::StartAndEndCoordinates* request, ::routing::v1::ShortestPathResult* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::routing::v1::ShortestPathResult>* AsyncFindShortestPathRaw(::grpc::ClientContext* context, const ::routing::v1::StartAndEndCoordinates& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::routing::v1::ShortestPathResult>* PrepareAsyncFindShortestPathRaw(::grpc::ClientContext* context, const ::routing::v1::StartAndEndCoordinates& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::routing::v1::ShortestPathResult>* AsyncFindTimeOptimalPathRaw(::grpc::ClientContext* context, const ::routing::v1::StartAndEndCoordinates& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::routing::v1::ShortestPathResult>* PrepareAsyncFindTimeOptimalPathRaw(::grpc::ClientContext* context, const ::routing::v1::StartAndEndCoordinates& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_FindShortestPath_;
    const ::grpc::internal::RpcMethod rpcmethod_FindTimeOptimalPath_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status FindShortestPath(::grpc::ServerContext* context, const ::routing::v1::StartAndEndCoordinates* request, ::routing::v1::ShortestPathResult* response);
    virtual ::grpc::Status FindTimeOptimalPath(::grpc::ServerContext* context, const ::routing::v1::StartAndEndCoordinates* request, ::routing::v1::ShortestPathResult* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_FindShortestPath : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_FindShortestPath() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_FindShortestPath() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FindShortestPath(::grpc::ServerContext* /*context*/, const ::routing::v1::StartAndEndCoordinates* /*request*/, ::routing::v1::ShortestPathResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFindShortestPath(::grpc::ServerContext* context, ::routing::v1::StartAndEndCoordinates* request, ::grpc::ServerAsyncResponseWriter< ::routing::v1::ShortestPathResult>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_FindTimeOptimalPath : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_FindTimeOptimalPath() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_FindTimeOptimalPath() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FindTimeOptimalPath(::grpc::ServerContext* /*context*/, const ::routing::v1::StartAndEndCoordinates* /*request*/, ::routing::v1::ShortestPathResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFindTimeOptimalPath(::grpc::ServerContext* context, ::routing::v1::StartAndEndCoordinates* request, ::grpc::ServerAsyncResponseWriter< ::routing::v1::ShortestPathResult>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_FindShortestPath<WithAsyncMethod_FindTimeOptimalPath<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_FindShortestPath : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_FindShortestPath() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::routing::v1::StartAndEndCoordinates, ::routing::v1::ShortestPathResult>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::routing::v1::StartAndEndCoordinates* request, ::routing::v1::ShortestPathResult* response) { return this->FindShortestPath(context, request, response); }));}
    void SetMessageAllocatorFor_FindShortestPath(
        ::grpc::MessageAllocator< ::routing::v1::StartAndEndCoordinates, ::routing::v1::ShortestPathResult>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::routing::v1::StartAndEndCoordinates, ::routing::v1::ShortestPathResult>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_FindShortestPath() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FindShortestPath(::grpc::ServerContext* /*context*/, const ::routing::v1::StartAndEndCoordinates* /*request*/, ::routing::v1::ShortestPathResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* FindShortestPath(
      ::grpc::CallbackServerContext* /*context*/, const ::routing::v1::StartAndEndCoordinates* /*request*/, ::routing::v1::ShortestPathResult* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_FindTimeOptimalPath : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_FindTimeOptimalPath() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::routing::v1::StartAndEndCoordinates, ::routing::v1::ShortestPathResult>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::routing::v1::StartAndEndCoordinates* request, ::routing::v1::ShortestPathResult* response) { return this->FindTimeOptimalPath(context, request, response); }));}
    void SetMessageAllocatorFor_FindTimeOptimalPath(
        ::grpc::MessageAllocator< ::routing::v1::StartAndEndCoordinates, ::routing::v1::ShortestPathResult>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::routing::v1::StartAndEndCoordinates, ::routing::v1::ShortestPathResult>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_FindTimeOptimalPath() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FindTimeOptimalPath(::grpc::ServerContext* /*context*/, const ::routing::v1::StartAndEndCoordinates* /*request*/, ::routing::v1::ShortestPathResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* FindTimeOptimalPath(
      ::grpc::CallbackServerContext* /*context*/, const ::routing::v1::StartAndEndCoordinates* /*request*/, ::routing::v1::ShortestPathResult* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_FindShortestPath<WithCallbackMethod_FindTimeOptimalPath<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_FindShortestPath : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_FindShortestPath() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_FindShortestPath() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FindShortestPath(::grpc::ServerContext* /*context*/, const ::routing::v1::StartAndEndCoordinates* /*request*/, ::routing::v1::ShortestPathResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_FindTimeOptimalPath : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_FindTimeOptimalPath() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_FindTimeOptimalPath() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FindTimeOptimalPath(::grpc::ServerContext* /*context*/, const ::routing::v1::StartAndEndCoordinates* /*request*/, ::routing::v1::ShortestPathResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_FindShortestPath : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_FindShortestPath() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_FindShortestPath() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FindShortestPath(::grpc::ServerContext* /*context*/, const ::routing::v1::StartAndEndCoordinates* /*request*/, ::routing::v1::ShortestPathResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFindShortestPath(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_FindTimeOptimalPath : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_FindTimeOptimalPath() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_FindTimeOptimalPath() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FindTimeOptimalPath(::grpc::ServerContext* /*context*/, const ::routing::v1::StartAndEndCoordinates* /*request*/, ::routing::v1::ShortestPathResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFindTimeOptimalPath(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_FindShortestPath : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_FindShortestPath() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->FindShortestPath(context, request, response); }));
    }
    ~WithRawCallbackMethod_FindShortestPath() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FindShortestPath(::grpc::ServerContext* /*context*/, const ::routing::v1::StartAndEndCoordinates* /*request*/, ::routing::v1::ShortestPathResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* FindShortestPath(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_FindTimeOptimalPath : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_FindTimeOptimalPath() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->FindTimeOptimalPath(context, request, response); }));
    }
    ~WithRawCallbackMethod_FindTimeOptimalPath() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status FindTimeOptimalPath(::grpc::ServerContext* /*context*/, const ::routing::v1::StartAndEndCoordinates* /*request*/, ::routing::v1::ShortestPathResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* FindTimeOptimalPath(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_FindShortestPath : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_FindShortestPath() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::routing::v1::StartAndEndCoordinates, ::routing::v1::ShortestPathResult>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::routing::v1::StartAndEndCoordinates, ::routing::v1::ShortestPathResult>* streamer) {
                       return this->StreamedFindShortestPath(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_FindShortestPath() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status FindShortestPath(::grpc::ServerContext* /*context*/, const ::routing::v1::StartAndEndCoordinates* /*request*/, ::routing::v1::ShortestPathResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedFindShortestPath(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::routing::v1::StartAndEndCoordinates,::routing::v1::ShortestPathResult>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_FindTimeOptimalPath : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_FindTimeOptimalPath() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::routing::v1::StartAndEndCoordinates, ::routing::v1::ShortestPathResult>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::routing::v1::StartAndEndCoordinates, ::routing::v1::ShortestPathResult>* streamer) {
                       return this->StreamedFindTimeOptimalPath(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_FindTimeOptimalPath() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status FindTimeOptimalPath(::grpc::ServerContext* /*context*/, const ::routing::v1::StartAndEndCoordinates* /*request*/, ::routing::v1::ShortestPathResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedFindTimeOptimalPath(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::routing::v1::StartAndEndCoordinates,::routing::v1::ShortestPathResult>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_FindShortestPath<WithStreamedUnaryMethod_FindTimeOptimalPath<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_FindShortestPath<WithStreamedUnaryMethod_FindTimeOptimalPath<Service > > StreamedService;
};

}  // namespace v1
}  // namespace routing


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_find_5fpath_2eproto__INCLUDED