// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: find_path.proto
// Protobuf C++ Version: 7.34.1

#ifndef find_5fpath_2eproto_2epb_2eh
#define find_5fpath_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7034001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_find_5fpath_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_find_5fpath_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_find_5fpath_2eproto;
}  // extern "C"
namespace routing {
namespace v1 {
class ShortestPathResult;
struct ShortestPathResultDefaultTypeInternal;
extern ShortestPathResultDefaultTypeInternal _ShortestPathResult_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull ShortestPathResult_class_data_;
class StartAndEndCoordinates;
struct StartAndEndCoordinatesDefaultTypeInternal;
extern StartAndEndCoordinatesDefaultTypeInternal _StartAndEndCoordinates_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull StartAndEndCoordinates_class_data_;
}  // namespace v1
}  // namespace routing
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace routing {
namespace v1 {

// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED StartAndEndCoordinates final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:routing.v1.StartAndEndCoordinates) */ {
 public:
  inline StartAndEndCoordinates() : StartAndEndCoordinates(nullptr) {}
  ~StartAndEndCoordinates() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(StartAndEndCoordinates* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(StartAndEndCoordinates));
  }
#endif

  template <typename = void>
  explicit constexpr StartAndEndCoordinates(::google::protobuf::internal::ConstantInitialized);

  inline StartAndEndCoordinates(const StartAndEndCoordinates& from) : StartAndEndCoordinates(nullptr, from) {}
  inline StartAndEndCoordinates(StartAndEndCoordinates&& from) noexcept
      : StartAndEndCoordinates(nullptr, ::std::move(from)) {}
  inline StartAndEndCoordinates& operator=(const StartAndEndCoordinates& from) {
    CopyFrom(from);
    return *this;
  }
  inline StartAndEndCoordinates& operator=(StartAndEndCoordinates&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const StartAndEndCoordinates& default_instance() {
    return *reinterpret_cast<const StartAndEndCoordinates*>(
        &_StartAndEndCoordinates_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(StartAndEndCoordinates& a, StartAndEndCoordinates& b) { a.Swap(&b); }
  inline void Swap(StartAndEndCoordinates* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StartAndEndCoordinates* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] StartAndEndCoordinates* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<StartAndEndCoordinates>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const StartAndEndCoordinates& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const StartAndEndCoordinates& from) { StartAndEndCoordinates::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(StartAndEndCoordinates* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "routing.v1.StartAndEndCoordinates"; }

  explicit StartAndEndCoordinates(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  StartAndEndCoordinates(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const StartAndEndCoordinates& from);
  StartAndEndCoordinates(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, StartAndEndCoordinates&& from) noexcept
      : StartAndEndCoordinates(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kStartXCoordinateFieldNumber = 1,
    kStartYCoordinateFieldNumber = 2,
    kEndXCoordinateFieldNumber = 3,
    kEndYCoordinateFieldNumber = 4,
  };
  // double start_x_coordinate = 1 [json_name = "startXCoordinate"];
  void clear_start_x_coordinate() ;
  [[nodiscard]] double start_x_coordinate() const;
  void set_start_x_coordinate(double value);

  private:
  double _internal_start_x_coordinate() const;
  void _internal_set_start_x_coordinate(double value);

  public:
  // double start_y_coordinate = 2 [json_name = "startYCoordinate"];
  void clear_start_y_coordinate() ;
  [[nodiscard]] double start_y_coordinate() const;
  void set_start_y_coordinate(double value);

  private:
  double _internal_start_y_coordinate() const;
  void _internal_set_start_y_coordinate(double value);

  public:
  // double end_x_coordinate = 3 [json_name = "endXCoordinate"];
  void clear_end_x_coordinate() ;
  [[nodiscard]] double end_x_coordinate() const;
  void set_end_x_coordinate(double value);

  private:
  double _internal_end_x_coordinate() const;
  void _internal_set_end_x_coordinate(double value);

  public:
  // double end_y_coordinate = 4 [json_name = "endYCoordinate"];
  void clear_end_y_coordinate() ;
  [[nodiscard]] double end_y_coordinate() const;
  void set_end_y_coordinate(double value);

  private:
  double _internal_end_y_coordinate() const;
  void _internal_set_end_y_coordinate(double value);

  public:
  // @@protoc_insertion_point(class_scope:routing.v1.StartAndEndCoordinates)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const StartAndEndCoordinates& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    double start_x_coordinate_;
    double start_y_coordinate_;
    double end_x_coordinate_;
    double end_y_coordinate_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_find_5fpath_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull StartAndEndCoordinates_class_data_;
// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED ShortestPathResult final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:routing.v1.ShortestPathResult) */ {
 public:
  inline ShortestPathResult() : ShortestPathResult(nullptr) {}
  ~ShortestPathResult() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(ShortestPathResult* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(ShortestPathResult));
  }
#endif

  template <typename = void>
  explicit constexpr ShortestPathResult(::google::protobuf::internal::ConstantInitialized);

  inline ShortestPathResult(const ShortestPathResult& from) : ShortestPathResult(nullptr, from) {}
  inline ShortestPathResult(ShortestPathResult&& from) noexcept
      : ShortestPathResult(nullptr, ::std::move(from)) {}
  inline ShortestPathResult& operator=(const ShortestPathResult& from) {
    CopyFrom(from);
    return *this;
  }
  inline ShortestPathResult& operator=(ShortestPathResult&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  [[nodiscard]] inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  [[nodiscard]] static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL
  GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  [[nodiscard]] static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  [[nodiscard]] static const ShortestPathResult& default_instance() {
    return *reinterpret_cast<const ShortestPathResult*>(
        &_ShortestPathResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(ShortestPathResult& a, ShortestPathResult& b) { a.Swap(&b); }
  inline void Swap(ShortestPathResult* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ShortestPathResult* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] ShortestPathResult* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<ShortestPathResult>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ShortestPathResult& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ShortestPathResult& from) { ShortestPathResult::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(ShortestPathResult* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "routing.v1.ShortestPathResult"; }

  explicit ShortestPathResult(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  ShortestPathResult(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const ShortestPathResult& from);
  ShortestPathResult(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, ShortestPathResult&& from) noexcept
      : ShortestPathResult(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  [[nodiscard]] ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPathFieldNumber = 3,
    kPointsFieldNumber = 4,
    kDistanceFieldNumber = 2,
    kPathExistsFieldNumber = 1,
  };
  // repeated uint64 path = 3 [json_name = "path"];
  [[nodiscard]] int path_size()
      const;
  private:
  int _internal_path_size() const;

  public:
  void clear_path() ;
  [[nodiscard]] ::uint64_t path(int index) const;
  void set_path(int index, ::uint64_t value);
  void add_path(::uint64_t value);
  [[nodiscard]] const ::google::protobuf::RepeatedField<::uint64_t>& path() const;
  ::google::protobuf::RepeatedField<::uint64_t>* PROTOBUF_NONNULL mutable_path();

  private:
  const ::google::protobuf::RepeatedField<::uint64_t>& _internal_path() const;
  ::google::protobuf::RepeatedField<::uint64_t>* PROTOBUF_NONNULL _internal_mutable_path();

  public:
  // .routing.v1.StartAndEndCoordinates points = 4 [json_name = "points"];
  [[nodiscard]] bool has_points()
      const;
  void clear_points() ;
  [[nodiscard]] const ::routing::v1::StartAndEndCoordinates& points() const;
  [[nodiscard]] ::routing::v1::StartAndEndCoordinates* PROTOBUF_NULLABLE release_points();
  ::routing::v1::StartAndEndCoordinates* PROTOBUF_NONNULL mutable_points();
  void set_allocated_points(::routing::v1::StartAndEndCoordinates* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_points(::routing::v1::StartAndEndCoordinates* PROTOBUF_NULLABLE value);
  ::routing::v1::StartAndEndCoordinates* PROTOBUF_NULLABLE unsafe_arena_release_points();

  private:
  const ::routing::v1::StartAndEndCoordinates& _internal_points() const;
  ::routing::v1::StartAndEndCoordinates* PROTOBUF_NONNULL _internal_mutable_points();

  public:
  // double distance = 2 [json_name = "distance"];
  void clear_distance() ;
  [[nodiscard]] double distance() const;
  void set_distance(double value);

  private:
  double _internal_distance() const;
  void _internal_set_distance(double value);

  public:
  // bool path_exists = 1 [json_name = "pathExists"];
  void clear_path_exists() ;
  [[nodiscard]] bool path_exists() const;
  void set_path_exists(bool value);

  private:
  bool _internal_path_exists() const;
  void _internal_set_path_exists(bool value);

  public:
  // @@protoc_insertion_point(class_scope:routing.v1.ShortestPathResult)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const ShortestPathResult& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<::uint64_t> path_;
    ::google::protobuf::internal::CachedSize _path_cached_byte_size_;
    ::routing::v1::StartAndEndCoordinates* PROTOBUF_NULLABLE points_;
    double distance_;
    bool path_exists_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_find_5fpath_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull ShortestPathResult_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// StartAndEndCoordinates

// double start_x_coordinate = 1 [json_name = "startXCoordinate"];
inline void StartAndEndCoordinates::clear_start_x_coordinate() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.start_x_coordinate_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline double StartAndEndCoordinates::start_x_coordinate() const {
  // @@protoc_insertion_point(field_get:routing.v1.StartAndEndCoordinates.start_x_coordinate)
  return _internal_start_x_coordinate();
}
inline void StartAndEndCoordinates::set_start_x_coordinate(double value) {
  _internal_set_start_x_coordinate(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:routing.v1.StartAndEndCoordinates.start_x_coordinate)
}
inline double StartAndEndCoordinates::_internal_start_x_coordinate() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.start_x_coordinate_;
}
inline void StartAndEndCoordinates::_internal_set_start_x_coordinate(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.start_x_coordinate_ = value;
}

// double start_y_coordinate = 2 [json_name = "startYCoordinate"];
inline void StartAndEndCoordinates::clear_start_y_coordinate() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.start_y_coordinate_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline double StartAndEndCoordinates::start_y_coordinate() const {
  // @@protoc_insertion_point(field_get:routing.v1.StartAndEndCoordinates.start_y_coordinate)
  return _internal_start_y_coordinate();
}
inline void StartAndEndCoordinates::set_start_y_coordinate(double value) {
  _internal_set_start_y_coordinate(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:routing.v1.StartAndEndCoordinates.start_y_coordinate)
}
inline double StartAndEndCoordinates::_internal_start_y_coordinate() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.start_y_coordinate_;
}
inline void StartAndEndCoordinates::_internal_set_start_y_coordinate(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.start_y_coordinate_ = value;
}

// double end_x_coordinate = 3 [json_name = "endXCoordinate"];
inline void StartAndEndCoordinates::clear_end_x_coordinate() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.end_x_coordinate_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline double StartAndEndCoordinates::end_x_coordinate() const {
  // @@protoc_insertion_point(field_get:routing.v1.StartAndEndCoordinates.end_x_coordinate)
  return _internal_end_x_coordinate();
}
inline void StartAndEndCoordinates::set_end_x_coordinate(double value) {
  _internal_set_end_x_coordinate(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:routing.v1.StartAndEndCoordinates.end_x_coordinate)
}
inline double StartAndEndCoordinates::_internal_end_x_coordinate() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.end_x_coordinate_;
}
inline void StartAndEndCoordinates::_internal_set_end_x_coordinate(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.end_x_coordinate_ = value;
}

// double end_y_coordinate = 4 [json_name = "endYCoordinate"];
inline void StartAndEndCoordinates::clear_end_y_coordinate() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.end_y_coordinate_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline double StartAndEndCoordinates::end_y_coordinate() const {
  // @@protoc_insertion_point(field_get:routing.v1.StartAndEndCoordinates.end_y_coordinate)
  return _internal_end_y_coordinate();
}
inline void StartAndEndCoordinates::set_end_y_coordinate(double value) {
  _internal_set_end_y_coordinate(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:routing.v1.StartAndEndCoordinates.end_y_coordinate)
}
inline double StartAndEndCoordinates::_internal_end_y_coordinate() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.end_y_coordinate_;
}
inline void StartAndEndCoordinates::_internal_set_end_y_coordinate(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.end_y_coordinate_ = value;
}

// -------------------------------------------------------------------

// ShortestPathResult

// bool path_exists = 1 [json_name = "pathExists"];
inline void ShortestPathResult::clear_path_exists() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.path_exists_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline bool ShortestPathResult::path_exists() const {
  // @@protoc_insertion_point(field_get:routing.v1.ShortestPathResult.path_exists)
  return _internal_path_exists();
}
inline void ShortestPathResult::set_path_exists(bool value) {
  _internal_set_path_exists(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:routing.v1.ShortestPathResult.path_exists)
}
inline bool ShortestPathResult::_internal_path_exists() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.path_exists_;
}
inline void ShortestPathResult::_internal_set_path_exists(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.path_exists_ = value;
}

// double distance = 2 [json_name = "distance"];
inline void ShortestPathResult::clear_distance() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.distance_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline double ShortestPathResult::distance() const {
  // @@protoc_insertion_point(field_get:routing.v1.ShortestPathResult.distance)
  return _internal_distance();
}
inline void ShortestPathResult::set_distance(double value) {
  _internal_set_distance(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:routing.v1.ShortestPathResult.distance)
}
inline double ShortestPathResult::_internal_distance() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.distance_;
}
inline void ShortestPathResult::_internal_set_distance(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.distance_ = value;
}

// repeated uint64 path = 3 [json_name = "path"];
inline int ShortestPathResult::_internal_path_size() const {
  return _internal_path().size();
}
inline int ShortestPathResult::path_size() const {
  return _internal_path_size();
}
inline void ShortestPathResult::clear_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.path_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::uint64_t ShortestPathResult::path(int index) const {
  // @@protoc_insertion_point(field_get:routing.v1.ShortestPathResult.path)
  return _internal_path().Get(index);
}
inline void ShortestPathResult::set_path(int index, ::uint64_t value) {
  _internal_mutable_path()->Set(index, value);
  // @@protoc_insertion_point(field_set:routing.v1.ShortestPathResult.path)
}
inline void ShortestPathResult::add_path(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_path()->InternalAddWithArena(
      internal_visibility(), GetArena(), value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:routing.v1.ShortestPathResult.path)
}
inline const ::google::protobuf::RepeatedField<::uint64_t>& ShortestPathResult::path() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:routing.v1.ShortestPathResult.path)
  return _internal_path();
}
inline ::google::protobuf::RepeatedField<::uint64_t>* PROTOBUF_NONNULL ShortestPathResult::mutable_path()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:routing.v1.ShortestPathResult.path)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_path();
}
inline const ::google::protobuf::RepeatedField<::uint64_t>&
ShortestPathResult::_internal_path() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.path_;
}
inline ::google::protobuf::RepeatedField<::uint64_t>* PROTOBUF_NONNULL
ShortestPathResult::_internal_mutable_path() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.path_;
}

// .routing.v1.StartAndEndCoordinates points = 4 [json_name = "points"];
inline bool ShortestPathResult::has_points() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  PROTOBUF_ASSUME(!value || _impl_.points_ != nullptr);
  return value;
}
inline void ShortestPathResult::clear_points() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.points_ != nullptr) _impl_.points_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::routing::v1::StartAndEndCoordinates& ShortestPathResult::_internal_points() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::routing::v1::StartAndEndCoordinates* p = _impl_.points_;
  return p != nullptr ? *p : reinterpret_cast<const ::routing::v1::StartAndEndCoordinates&>(::routing::v1::_StartAndEndCoordinates_default_instance_);
}
inline const ::routing::v1::StartAndEndCoordinates& ShortestPathResult::points() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:routing.v1.ShortestPathResult.points)
  return _internal_points();
}
inline void ShortestPathResult::unsafe_arena_set_allocated_points(
    ::routing::v1::StartAndEndCoordinates* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.points_);
  }
  _impl_.points_ = reinterpret_cast<::routing::v1::StartAndEndCoordinates*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:routing.v1.ShortestPathResult.points)
}
inline ::routing::v1::StartAndEndCoordinates* PROTOBUF_NULLABLE ShortestPathResult::release_points() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::routing::v1::StartAndEndCoordinates* released = _impl_.points_;
  _impl_.points_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::routing::v1::StartAndEndCoordinates* PROTOBUF_NULLABLE ShortestPathResult::unsafe_arena_release_points() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:routing.v1.ShortestPathResult.points)

  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::routing::v1::StartAndEndCoordinates* temp = _impl_.points_;
  _impl_.points_ = nullptr;
  return temp;
}
inline ::routing::v1::StartAndEndCoordinates* PROTOBUF_NONNULL ShortestPathResult::_internal_mutable_points() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.points_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::routing::v1::StartAndEndCoordinates>(GetArena());
    _impl_.points_ = reinterpret_cast<::routing::v1::StartAndEndCoordinates*>(p);
  }
  return _impl_.points_;
}
inline ::routing::v1::StartAndEndCoordinates* PROTOBUF_NONNULL ShortestPathResult::mutable_points()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::routing::v1::StartAndEndCoordinates* _msg = _internal_mutable_points();
  // @@protoc_insertion_point(field_mutable:routing.v1.ShortestPathResult.points)
  return _msg;
}
inline void ShortestPathResult::set_allocated_points(::routing::v1::StartAndEndCoordinates* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.points_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }

  _impl_.points_ = reinterpret_cast<::routing::v1::StartAndEndCoordinates*>(value);
  // @@protoc_insertion_point(field_set_allocated:routing.v1.ShortestPathResult.points)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace routing


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // find_5fpath_2eproto_2epb_2eh