// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: find_path.proto

#include "find_path.pb.h"
#include "find_path.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace routing {
namespace v1 {

static const char* PathService_method_names[] = {
  "/routing.v1.PathService/FindShortestPath",
  "/routing.v1.PathService/FindTimeOptimalPath",
};

std::unique_ptr< PathService::Stub> PathService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< PathService::Stub> stub(new PathService::Stub(channel, options));
  return stub;
}

PathService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_FindShortestPath_(PathService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_FindTimeOptimalPath_(PathService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status PathService::Stub::FindShortestPath(::grpc::ClientContext* context, const ::routing::v1::StartAndEndCoordinates& request, ::routing::v1::ShortestPathResult* response) {
  return ::grpc::internal::BlockingUnaryCall< ::routing::v1::StartAndEndCoordinates, ::routing::v1::ShortestPathResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_FindShortestPath_, context, request, response);
}

void PathService::Stub::async::FindShortestPath(::grpc::ClientContext* context, const ::routing::v1::StartAndEndCoordinates* request, ::routing::v1::ShortestPathResult* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::routing::v1::StartAndEndCoordinates, ::routing::v1::ShortestPathResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FindShortestPath_, context, request, response, std::move(f));
}

void PathService::Stub::async::FindShortestPath(::grpc::ClientContext* context, const ::routing::v1::StartAndEndCoordinates* request, ::routing::v1::ShortestPathResult* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FindShortestPath_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::routing::v1::ShortestPathResult>* PathService::Stub::PrepareAsyncFindShortestPathRaw(::grpc::ClientContext* context, const ::routing::v1::StartAndEndCoordinates& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::routing::v1::ShortestPathResult, ::routing::v1::StartAndEndCoordinates, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_FindShortestPath_, context, request);
}

::grpc::ClientAsyncResponseReader< ::routing::v1::ShortestPathResult>* PathService::Stub::AsyncFindShortestPathRaw(::grpc::ClientContext* context, const ::routing::v1::StartAndEndCoordinates& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncFindShortestPathRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status PathService::Stub::FindTimeOptimalPath(::grpc::ClientContext* context, const ::routing::v1::StartAndEndCoordinates& request, ::routing::v1::ShortestPathResult* response) {
  return ::grpc::internal::BlockingUnaryCall< ::routing::v1::StartAndEndCoordinates, ::routing::v1::ShortestPathResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_FindTimeOptimalPath_, context, request, response);
}

void PathService::Stub::async::FindTimeOptimalPath(::grpc::ClientContext* context, const ::routing::v1::StartAndEndCoordinates* request, ::routing::v1::ShortestPathResult* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::routing::v1::StartAndEndCoordinates, ::routing::v1::ShortestPathResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FindTimeOptimalPath_, context, request, response, std::move(f));
}

void PathService::Stub::async::FindTimeOptimalPath(::grpc::ClientContext* context, const ::routing::v1::StartAndEndCoordinates* request, ::routing::v1::ShortestPathResult* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FindTimeOptimalPath_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::routing::v1::ShortestPathResult>* PathService::Stub::PrepareAsyncFindTimeOptimalPathRaw(::grpc::ClientContext* context, const ::routing::v1::StartAndEndCoordinates& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::routing::v1::ShortestPathResult, ::routing::v1::StartAndEndCoordinates, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_FindTimeOptimalPath_, context, request);
}

::grpc::ClientAsyncResponseReader< ::routing::v1::ShortestPathResult>* PathService::Stub::AsyncFindTimeOptimalPathRaw(::grpc::ClientContext* context, const ::routing::v1::StartAndEndCoordinates& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncFindTimeOptimalPathRaw(context, request, cq);
  result->StartCall();
  return result;
}

PathService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PathService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PathService::Service, ::routing::v1::StartAndEndCoordinates, ::routing::v1::ShortestPathResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PathService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::routing::v1::StartAndEndCoordinates* req,
             ::routing::v1::ShortestPathResult* resp) {
               return service->FindShortestPath(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PathService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PathService::Service, ::routing::v1::StartAndEndCoordinates, ::routing::v1::ShortestPathResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](PathService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::routing::v1::StartAndEndCoordinates* req,
             ::routing::v1::ShortestPathResult* resp) {
               return service->FindTimeOptimalPath(ctx, req, resp);
             }, this)));
}

PathService::Service::~Service() {
}

::grpc::Status PathService::Service::FindShortestPath(::grpc::ServerContext* context, const ::routing::v1::StartAndEndCoordinates* request, ::routing::v1::ShortestPathResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status PathService::Service::FindTimeOptimalPath(::grpc::ServerContext* context, const ::routing::v1::StartAndEndCoordinates* request, ::routing::v1::ShortestPathResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace routing
}  // namespace v1
#include <grpcpp/ports_undef.inc>