// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: find_path.proto
// Protobuf C++ Version: 7.34.1

#include "find_path.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace routing {
namespace v1 {

inline constexpr StartAndEndCoordinates::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        start_x_coordinate_{0},
        start_y_coordinate_{0},
        end_x_coordinate_{0},
        end_y_coordinate_{0} {}

template <typename>
constexpr StartAndEndCoordinates::StartAndEndCoordinates(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(StartAndEndCoordinates_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct StartAndEndCoordinatesDefaultTypeInternal {
  constexpr StartAndEndCoordinatesDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~StartAndEndCoordinatesDefaultTypeInternal() {}
  union {
    StartAndEndCoordinates _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 StartAndEndCoordinatesDefaultTypeInternal _StartAndEndCoordinates_default_instance_;

inline constexpr ShortestPathResult::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        #ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_FIELD
        path_{visibility, ::_pbi::InternalMetadataOffset::Build<
            ::routing::v1::ShortestPathResult,
            PROTOBUF_FIELD_OFFSET(::routing::v1::ShortestPathResult, _impl_.path_)>()
        }
        #else
        path_ {}
        #endif
        ,
        _path_cached_byte_size_{0},
        points_{nullptr},
        distance_{0},
        path_exists_{false} {}

template <typename>
constexpr ShortestPathResult::ShortestPathResult(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ShortestPathResult_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
struct ShortestPathResultDefaultTypeInternal {
  constexpr ShortestPathResultDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ShortestPathResultDefaultTypeInternal() {}
  union {
    ShortestPathResult _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ShortestPathResultDefaultTypeInternal _ShortestPathResult_default_instance_;
}  // namespace v1
}  // namespace routing
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_find_5fpath_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_find_5fpath_2eproto = nullptr;
const ::uint32_t
    TableStruct_find_5fpath_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::routing::v1::StartAndEndCoordinates, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::routing::v1::StartAndEndCoordinates, _impl_.start_x_coordinate_),
        PROTOBUF_FIELD_OFFSET(::routing::v1::StartAndEndCoordinates, _impl_.start_y_coordinate_),
        PROTOBUF_FIELD_OFFSET(::routing::v1::StartAndEndCoordinates, _impl_.end_x_coordinate_),
        PROTOBUF_FIELD_OFFSET(::routing::v1::StartAndEndCoordinates, _impl_.end_y_coordinate_),
        0,
        1,
        2,
        3,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::routing::v1::ShortestPathResult, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::routing::v1::ShortestPathResult, _impl_.path_exists_),
        PROTOBUF_FIELD_OFFSET(::routing::v1::ShortestPathResult, _impl_.distance_),
        PROTOBUF_FIELD_OFFSET(::routing::v1::ShortestPathResult, _impl_.path_),
        PROTOBUF_FIELD_OFFSET(::routing::v1::ShortestPathResult, _impl_.points_),
        3,
        2,
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::routing::v1::StartAndEndCoordinates)},
        {11, sizeof(::routing::v1::ShortestPathResult)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::routing::v1::_StartAndEndCoordinates_default_instance_._instance,
    &::routing::v1::_ShortestPathResult_default_instance_._instance,
};
const char descriptor_table_protodef_find_5fpath_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\017find_path.proto\022\nrouting.v1\"\310\001\n\026StartA"
    "ndEndCoordinates\022,\n\022start_x_coordinate\030\001"
    " \001(\001R\020startXCoordinate\022,\n\022start_y_coordi"
    "nate\030\002 \001(\001R\020startYCoordinate\022(\n\020end_x_co"
    "ordinate\030\003 \001(\001R\016endXCoordinate\022(\n\020end_y_"
    "coordinate\030\004 \001(\001R\016endYCoordinate\"\241\001\n\022Sho"
    "rtestPathResult\022\037\n\013path_exists\030\001 \001(\010R\npa"
    "thExists\022\032\n\010distance\030\002 \001(\001R\010distance\022\022\n\004"
    "path\030\003 \003(\004R\004path\022:\n\006points\030\004 \001(\0132\".routi"
    "ng.v1.StartAndEndCoordinatesR\006points2\300\001\n"
    "\013PathService\022V\n\020FindShortestPath\022\".routi"
    "ng.v1.StartAndEndCoordinates\032\036.routing.v"
    "1.ShortestPathResult\022Y\n\023FindTimeOptimalP"
    "ath\022\".routing.v1.StartAndEndCoordinates\032"
    "\036.routing.v1.ShortestPathResultB\r\252\002\nRout"
    "ing.V1b\006proto3"
};
static ::absl::once_flag descriptor_table_find_5fpath_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_find_5fpath_2eproto = {
    false,
    false,
    614,
    descriptor_table_protodef_find_5fpath_2eproto,
    "find_path.proto",
    &descriptor_table_find_5fpath_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_find_5fpath_2eproto::offsets,
    file_level_enum_descriptors_find_5fpath_2eproto,
    file_level_service_descriptors_find_5fpath_2eproto,
};
namespace routing {
namespace v1 {
// ===================================================================

class StartAndEndCoordinates::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<StartAndEndCoordinates>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(StartAndEndCoordinates, _impl_._has_bits_);
};

StartAndEndCoordinates::StartAndEndCoordinates(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, StartAndEndCoordinates_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:routing.v1.StartAndEndCoordinates)
}
StartAndEndCoordinates::StartAndEndCoordinates(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const StartAndEndCoordinates& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, StartAndEndCoordinates_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE StartAndEndCoordinates::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void StartAndEndCoordinates::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, start_x_coordinate_),
           0,
           offsetof(Impl_, end_y_coordinate_) -
               offsetof(Impl_, start_x_coordinate_) +
               sizeof(Impl_::end_y_coordinate_));
}
StartAndEndCoordinates::~StartAndEndCoordinates() {
  // @@protoc_insertion_point(destructor:routing.v1.StartAndEndCoordinates)
  SharedDtor(*this);
}
inline void StartAndEndCoordinates::SharedDtor(MessageLite& self) {
  StartAndEndCoordinates& this_ = static_cast<StartAndEndCoordinates&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL StartAndEndCoordinates::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) StartAndEndCoordinates(arena);
}
constexpr auto StartAndEndCoordinates::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(StartAndEndCoordinates),
                                            alignof(StartAndEndCoordinates));
}
constexpr auto StartAndEndCoordinates::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_StartAndEndCoordinates_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &StartAndEndCoordinates::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<StartAndEndCoordinates>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &StartAndEndCoordinates::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<StartAndEndCoordinates>(), &StartAndEndCoordinates::ByteSizeLong,
              &StartAndEndCoordinates::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(StartAndEndCoordinates, _impl_._cached_size_),
          false,
      },
      &StartAndEndCoordinates::kDescriptorMethods,
      &descriptor_table_find_5fpath_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull StartAndEndCoordinates_class_data_ =
        StartAndEndCoordinates::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
StartAndEndCoordinates::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&StartAndEndCoordinates_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(StartAndEndCoordinates_class_data_.tc_table);
  return StartAndEndCoordinates_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 0, 2>
StartAndEndCoordinates::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(StartAndEndCoordinates, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    StartAndEndCoordinates_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::routing::v1::StartAndEndCoordinates>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // double end_y_coordinate = 4 [json_name = "endYCoordinate"];
    {::_pbi::TcParser::FastF64S1,
     {33, 3, 0,
      PROTOBUF_FIELD_OFFSET(StartAndEndCoordinates, _impl_.end_y_coordinate_)}},
    // double start_x_coordinate = 1 [json_name = "startXCoordinate"];
    {::_pbi::TcParser::FastF64S1,
     {9, 0, 0,
      PROTOBUF_FIELD_OFFSET(StartAndEndCoordinates, _impl_.start_x_coordinate_)}},
    // double start_y_coordinate = 2 [json_name = "startYCoordinate"];
    {::_pbi::TcParser::FastF64S1,
     {17, 1, 0,
      PROTOBUF_FIELD_OFFSET(StartAndEndCoordinates, _impl_.start_y_coordinate_)}},
    // double end_x_coordinate = 3 [json_name = "endXCoordinate"];
    {::_pbi::TcParser::FastF64S1,
     {25, 2, 0,
      PROTOBUF_FIELD_OFFSET(StartAndEndCoordinates, _impl_.end_x_coordinate_)}},
  }}, {{
    65535, 65535
  }}, {{
    // double start_x_coordinate = 1 [json_name = "startXCoordinate"];
    {PROTOBUF_FIELD_OFFSET(StartAndEndCoordinates, _impl_.start_x_coordinate_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // double start_y_coordinate = 2 [json_name = "startYCoordinate"];
    {PROTOBUF_FIELD_OFFSET(StartAndEndCoordinates, _impl_.start_y_coordinate_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // double end_x_coordinate = 3 [json_name = "endXCoordinate"];
    {PROTOBUF_FIELD_OFFSET(StartAndEndCoordinates, _impl_.end_x_coordinate_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // double end_y_coordinate = 4 [json_name = "endYCoordinate"];
    {PROTOBUF_FIELD_OFFSET(StartAndEndCoordinates, _impl_.end_y_coordinate_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void StartAndEndCoordinates::Clear() {
// @@protoc_insertion_point(message_clear_start:routing.v1.StartAndEndCoordinates)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    ::memset(&_impl_.start_x_coordinate_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.end_y_coordinate_) -
        reinterpret_cast<char*>(&_impl_.start_x_coordinate_)) + sizeof(_impl_.end_y_coordinate_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL StartAndEndCoordinates::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const StartAndEndCoordinates& this_ = static_cast<const StartAndEndCoordinates&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL StartAndEndCoordinates::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const StartAndEndCoordinates& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:routing.v1.StartAndEndCoordinates)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // double start_x_coordinate = 1 [json_name = "startXCoordinate"];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_start_x_coordinate()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          1, this_._internal_start_x_coordinate(), target);
    }
  }

  // double start_y_coordinate = 2 [json_name = "startYCoordinate"];
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_start_y_coordinate()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          2, this_._internal_start_y_coordinate(), target);
    }
  }

  // double end_x_coordinate = 3 [json_name = "endXCoordinate"];
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_end_x_coordinate()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          3, this_._internal_end_x_coordinate(), target);
    }
  }

  // double end_y_coordinate = 4 [json_name = "endYCoordinate"];
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_end_y_coordinate()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          4, this_._internal_end_y_coordinate(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:routing.v1.StartAndEndCoordinates)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t StartAndEndCoordinates::ByteSizeLong(const MessageLite& base) {
  const StartAndEndCoordinates& this_ = static_cast<const StartAndEndCoordinates&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t StartAndEndCoordinates::ByteSizeLong() const {
  const StartAndEndCoordinates& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:routing.v1.StartAndEndCoordinates)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    // double start_x_coordinate = 1 [json_name = "startXCoordinate"];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_start_x_coordinate()) != 0) {
        total_size += 9;
      }
    }
    // double start_y_coordinate = 2 [json_name = "startYCoordinate"];
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_start_y_coordinate()) != 0) {
        total_size += 9;
      }
    }
    // double end_x_coordinate = 3 [json_name = "endXCoordinate"];
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_end_x_coordinate()) != 0) {
        total_size += 9;
      }
    }
    // double end_y_coordinate = 4 [json_name = "endYCoordinate"];
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_end_y_coordinate()) != 0) {
        total_size += 9;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void StartAndEndCoordinates::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<StartAndEndCoordinates*>(&to_msg);
  auto& from = static_cast<const StartAndEndCoordinates&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:routing.v1.StartAndEndCoordinates)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (::absl::bit_cast<::uint64_t>(from._internal_start_x_coordinate()) != 0) {
        _this->_impl_.start_x_coordinate_ = from._impl_.start_x_coordinate_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (::absl::bit_cast<::uint64_t>(from._internal_start_y_coordinate()) != 0) {
        _this->_impl_.start_y_coordinate_ = from._impl_.start_y_coordinate_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (::absl::bit_cast<::uint64_t>(from._internal_end_x_coordinate()) != 0) {
        _this->_impl_.end_x_coordinate_ = from._impl_.end_x_coordinate_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (::absl::bit_cast<::uint64_t>(from._internal_end_y_coordinate()) != 0) {
        _this->_impl_.end_y_coordinate_ = from._impl_.end_y_coordinate_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void StartAndEndCoordinates::CopyFrom(const StartAndEndCoordinates& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:routing.v1.StartAndEndCoordinates)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void StartAndEndCoordinates::InternalSwap(StartAndEndCoordinates* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(StartAndEndCoordinates, _impl_.end_y_coordinate_)
      + sizeof(StartAndEndCoordinates::_impl_.end_y_coordinate_)
      - PROTOBUF_FIELD_OFFSET(StartAndEndCoordinates, _impl_.start_x_coordinate_)>(
          reinterpret_cast<char*>(&_impl_.start_x_coordinate_),
          reinterpret_cast<char*>(&other->_impl_.start_x_coordinate_));
}

::google::protobuf::Metadata StartAndEndCoordinates::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ShortestPathResult::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<ShortestPathResult>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ShortestPathResult, _impl_._has_bits_);
};

ShortestPathResult::ShortestPathResult(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ShortestPathResult_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:routing.v1.ShortestPathResult)
}
PROTOBUF_NDEBUG_INLINE ShortestPathResult::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::routing::v1::ShortestPathResult& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        #ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_FIELD
        path_{visibility, ::_pbi::InternalMetadataOffset::Build<
            ::routing::v1::ShortestPathResult,
            PROTOBUF_FIELD_OFFSET(::routing::v1::ShortestPathResult, _impl_.path_)>()
        , from.path_}
        #else
        path_ { visibility, arena, from.path_ }
        #endif
        ,
        _path_cached_byte_size_{0} {}

ShortestPathResult::ShortestPathResult(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ShortestPathResult& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ShortestPathResult_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ShortestPathResult* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.points_ = (CheckHasBit(cached_has_bits, 0x00000002U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.points_)
                : nullptr;
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, distance_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, distance_),
           offsetof(Impl_, path_exists_) -
               offsetof(Impl_, distance_) +
               sizeof(Impl_::path_exists_));

  // @@protoc_insertion_point(copy_constructor:routing.v1.ShortestPathResult)
}
PROTOBUF_NDEBUG_INLINE ShortestPathResult::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        #ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_FIELD
        path_{visibility, ::_pbi::InternalMetadataOffset::Build<
            ::routing::v1::ShortestPathResult,
            PROTOBUF_FIELD_OFFSET(::routing::v1::ShortestPathResult, _impl_.path_)>()
        }
        #else
        path_ { visibility, arena }
        #endif
        ,
        _path_cached_byte_size_{0} {}

inline void ShortestPathResult::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, points_),
           0,
           offsetof(Impl_, path_exists_) -
               offsetof(Impl_, points_) +
               sizeof(Impl_::path_exists_));
}
ShortestPathResult::~ShortestPathResult() {
  // @@protoc_insertion_point(destructor:routing.v1.ShortestPathResult)
  SharedDtor(*this);
}
inline void ShortestPathResult::SharedDtor(MessageLite& self) {
  ShortestPathResult& this_ = static_cast<ShortestPathResult&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.points_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ShortestPathResult::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ShortestPathResult(arena);
}
#ifdef PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_PTR_FIELD
constexpr auto ShortestPathResult::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ShortestPathResult),
                                            alignof(ShortestPathResult));
}
#else  // !PROTOBUF_INTERNAL_REMOVE_ARENA_PTRS_REPEATED_PTR_FIELD
constexpr auto ShortestPathResult::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(ShortestPathResult, _impl_.path_) +
          decltype(ShortestPathResult::_impl_.path_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(ShortestPathResult), alignof(ShortestPathResult), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&ShortestPathResult::PlacementNew_,
                                 sizeof(ShortestPathResult),
                                 alignof(ShortestPathResult));
  }
}
#endif
constexpr auto ShortestPathResult::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ShortestPathResult_default_instance_._instance,
          &_table_.header,
          nullptr,  // IsInitialized
          &ShortestPathResult::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ShortestPathResult>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ShortestPathResult::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ShortestPathResult>(), &ShortestPathResult::ByteSizeLong,
              &ShortestPathResult::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ShortestPathResult, _impl_._cached_size_),
          false,
      },
      &ShortestPathResult::kDescriptorMethods,
      &descriptor_table_find_5fpath_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ShortestPathResult_class_data_ =
        ShortestPathResult::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ShortestPathResult::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ShortestPathResult_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ShortestPathResult_class_data_.tc_table);
  return ShortestPathResult_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 1, 0, 2>
ShortestPathResult::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ShortestPathResult, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    ShortestPathResult_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::routing::v1::ShortestPathResult>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .routing.v1.StartAndEndCoordinates points = 4 [json_name = "points"];
    {::_pbi::TcParser::FastMtS1,
     {34, 1, 0,
      PROTOBUF_FIELD_OFFSET(ShortestPathResult, _impl_.points_)}},
    // bool path_exists = 1 [json_name = "pathExists"];
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ShortestPathResult, _impl_.path_exists_), 3>(),
     {8, 3, 0,
      PROTOBUF_FIELD_OFFSET(ShortestPathResult, _impl_.path_exists_)}},
    // double distance = 2 [json_name = "distance"];
    {::_pbi::TcParser::FastF64S1,
     {17, 2, 0,
      PROTOBUF_FIELD_OFFSET(ShortestPathResult, _impl_.distance_)}},
    // repeated uint64 path = 3 [json_name = "path"];
    {::_pbi::TcParser::FastV64P1,
     {26, 0, 0,
      PROTOBUF_FIELD_OFFSET(ShortestPathResult, _impl_.path_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool path_exists = 1 [json_name = "pathExists"];
    {PROTOBUF_FIELD_OFFSET(ShortestPathResult, _impl_.path_exists_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // double distance = 2 [json_name = "distance"];
    {PROTOBUF_FIELD_OFFSET(ShortestPathResult, _impl_.distance_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
    // repeated uint64 path = 3 [json_name = "path"];
    {PROTOBUF_FIELD_OFFSET(ShortestPathResult, _impl_.path_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kPackedUInt64)},
    // .routing.v1.StartAndEndCoordinates points = 4 [json_name = "points"];
    {PROTOBUF_FIELD_OFFSET(ShortestPathResult, _impl_.points_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::routing::v1::StartAndEndCoordinates>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void ShortestPathResult::Clear() {
// @@protoc_insertion_point(message_clear_start:routing.v1.ShortestPathResult)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _impl_.path_.Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(_impl_.points_ != nullptr);
      _impl_.points_->Clear();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000000cU)) {
    ::memset(&_impl_.distance_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.path_exists_) -
        reinterpret_cast<char*>(&_impl_.distance_)) + sizeof(_impl_.path_exists_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ShortestPathResult::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ShortestPathResult& this_ = static_cast<const ShortestPathResult&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ShortestPathResult::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ShortestPathResult& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:routing.v1.ShortestPathResult)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // bool path_exists = 1 [json_name = "pathExists"];
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_path_exists() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          1, this_._internal_path_exists(), target);
    }
  }

  // double distance = 2 [json_name = "distance"];
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (::absl::bit_cast<::uint64_t>(this_._internal_distance()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          2, this_._internal_distance(), target);
    }
  }

  // repeated uint64 path = 3 [json_name = "path"];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    {
      int byte_size = this_._impl_._path_cached_byte_size_.Get();
      if (byte_size > 0) {
        target = stream->WriteUInt64Packed(
            3, this_._internal_path(), byte_size, target);
      }
    }
  }

  // .routing.v1.StartAndEndCoordinates points = 4 [json_name = "points"];
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        4, *this_._impl_.points_, this_._impl_.points_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:routing.v1.ShortestPathResult)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ShortestPathResult::ByteSizeLong(const MessageLite& base) {
  const ShortestPathResult& this_ = static_cast<const ShortestPathResult&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ShortestPathResult::ByteSizeLong() const {
  const ShortestPathResult& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:routing.v1.ShortestPathResult)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    // repeated uint64 path = 3 [json_name = "path"];
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size +=
          ::_pbi::WireFormatLite::UInt64SizeWithPackedTagSize(
              this_._internal_path(), 1,
              this_._impl_._path_cached_byte_size_);
    }
    // .routing.v1.StartAndEndCoordinates points = 4 [json_name = "points"];
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.points_);
    }
    // double distance = 2 [json_name = "distance"];
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (::absl::bit_cast<::uint64_t>(this_._internal_distance()) != 0) {
        total_size += 9;
      }
    }
    // bool path_exists = 1 [json_name = "pathExists"];
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_path_exists() != 0) {
        total_size += 2;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ShortestPathResult::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<ShortestPathResult*>(&to_msg);
  auto& from = static_cast<const ShortestPathResult&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:routing.v1.ShortestPathResult)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_path()->MergeFrom(from._internal_path());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      ABSL_DCHECK(from._impl_.points_ != nullptr);
      if (_this->_impl_.points_ == nullptr) {
        _this->_impl_.points_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.points_);
      } else {
        _this->_impl_.points_->MergeFrom(*from._impl_.points_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (::absl::bit_cast<::uint64_t>(from._internal_distance()) != 0) {
        _this->_impl_.distance_ = from._impl_.distance_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_path_exists() != 0) {
        _this->_impl_.path_exists_ = from._impl_.path_exists_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void ShortestPathResult::CopyFrom(const ShortestPathResult& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:routing.v1.ShortestPathResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ShortestPathResult::InternalSwap(ShortestPathResult* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.path_.InternalSwap(&other->_impl_.path_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ShortestPathResult, _impl_.path_exists_)
      + sizeof(ShortestPathResult::_impl_.path_exists_)
      - PROTOBUF_FIELD_OFFSET(ShortestPathResult, _impl_.points_)>(
          reinterpret_cast<char*>(&_impl_.points_),
          reinterpret_cast<char*>(&other->_impl_.points_));
}

::google::protobuf::Metadata ShortestPathResult::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace routing
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_find_5fpath_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"